//! Shared GPU resources for 3D sprite rendering.
//!
//! All entity sprites (body / HP bar bg / HP bar fg / facing arrow) are
//! 3D Mesh nodes pointing to a single shared 1×1 quad SurfaceResource and
//! a per-color MaterialResource. Fyrox's renderer auto-instances Mesh nodes
//! sharing the same (SurfaceResource, Material) → one draw call per pair.

use fyrox::asset::untyped::ResourceKind;
use fyrox::core::algebra::Matrix4;
use fyrox::core::color::Color;
use fyrox::core::uuid::Uuid;
use fyrox::material::shader::{ShaderResource, ShaderResourceExtension};
use fyrox::material::{Material, MaterialProperty, MaterialResource};
use fyrox::scene::mesh::surface::{SurfaceData, SurfaceResource};
use std::sync::OnceLock;

#[derive(Debug)]
pub struct SharedSpriteResources {
    pub quad: SurfaceResource,

    pub mat_hero: MaterialResource,
    pub mat_creep: MaterialResource,
    pub mat_tower: MaterialResource,
    pub mat_projectile: MaterialResource,
    pub mat_default: MaterialResource,

    pub mat_hp_bg: MaterialResource,
    pub mat_hp_fg: MaterialResource,

    pub mat_facing: MaterialResource,
}

impl SharedSpriteResources {
    pub fn new() -> Self {
        let quad_data = SurfaceData::make_quad(&Matrix4::identity());
        let quad = SurfaceResource::new_embedded(quad_data);

        Self {
            quad,
            mat_hero: make_color_material(Color::from_rgba(50, 180, 50, 255)),
            mat_creep: make_color_material(Color::from_rgba(220, 40, 40, 255)),
            mat_tower: make_color_material(Color::from_rgba(50, 100, 220, 255)),
            mat_projectile: make_color_material(Color::from_rgba(255, 230, 50, 255)),
            mat_default: make_color_material(Color::from_rgba(200, 200, 200, 255)),
            mat_hp_bg: make_color_material(Color::from_rgba(0, 0, 0, 255)),
            mat_hp_fg: make_color_material(Color::from_rgba(0, 220, 0, 255)),
            mat_facing: make_color_material(Color::from_rgba(255, 200, 0, 255)),
        }
    }

    pub fn material_for(&self, entity_type: &str) -> &MaterialResource {
        match entity_type {
            "hero" => &self.mat_hero,
            "creep" | "enemy" => &self.mat_creep,
            "unit" | "tower" => &self.mat_tower,
            "bullet" | "projectile" => &self.mat_projectile,
            _ => &self.mat_default,
        }
    }

    /// Build a 3D Mesh node referencing the shared quad + given material.
    /// Caller sets local_transform afterwards (position, scale, rotation).
    pub fn build_mesh(
        &self,
        scene: &mut fyrox::scene::Scene,
        material: fyrox::material::MaterialResource,
    ) -> fyrox::core::pool::Handle<fyrox::scene::node::Node> {
        use fyrox::scene::base::BaseBuilder;
        use fyrox::scene::mesh::surface::SurfaceBuilder;
        use fyrox::scene::mesh::MeshBuilder;

        MeshBuilder::new(BaseBuilder::new())
            .with_surfaces(vec![SurfaceBuilder::new(self.quad.clone())
                .with_material(material)
                .build()])
            .build(&mut scene.graph)
            .to_base()
    }
}

/// Custom unlit sprite shader.
///
/// Why not Material::standard_2d() / standard_sprite()?
/// - standard_2d's Forward pass output is `ambientLight * vertexColor * diffuseTexture`,
///   it never reads `diffuseColor` (the property exists in the material struct but is
///   ignored by the GLSL).
/// - standard_sprite outputs `vertexColor * texture`.
/// - SurfaceData::make_quad() emits StaticVertex (position/normal/tex_coord/tangent only,
///   NO color attribute) → vertexColor reads as 0.0 → fragment is black regardless of
///   ambient or material color.
///
/// This shader skips lighting and vertex color, outputting `properties.diffuseColor *
/// diffuseTexture` (white fallback texture → just diffuseColor). Forward pass only;
/// GBuffer/shadow passes disabled like the other Standard*Sprite shaders.
const UNLIT_SPRITE_SHADER_SRC: &str = r##"(
    name: "OmfxUnlitSprite",

    resources: [
        (
            name: "diffuseTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "properties",
            kind: PropertyGroup([
                (
                    name: "diffuseColor",
                    kind: Color(r: 255, g: 255, b: 255, a: 255),
                ),
            ]),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
    ],

    disabled_passes: ["GBuffer", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Forward",
            draw_parameters: DrawParameters(
                cull_face: None,
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(LessOrEqual),
                blend: Some(BlendParameters(
                    func: BlendFunc(
                        sfactor: SrcAlpha,
                        dfactor: OneMinusSrcAlpha,
                        alpha_sfactor: SrcAlpha,
                        alpha_dfactor: OneMinusSrcAlpha,
                    ),
                    equation: BlendEquation(
                        rgb: Add,
                        alpha: Add
                    )
                )),
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
                r#"
                layout(location = 0) in vec3 vertexPosition;
                layout(location = 1) in vec2 vertexTexCoord;

                out vec2 texCoord;

                void main()
                {
                    texCoord = vertexTexCoord;
                    gl_Position = fyrox_instanceData.worldViewProjection * vec4(vertexPosition, 1.0);
                }
                "#,
            fragment_shader:
                r#"
                out vec4 FragColor;

                in vec2 texCoord;

                void main()
                {
                    FragColor = properties.diffuseColor * texture(diffuseTexture, texCoord);
                }
                "#,
        )
    ],
)"##;

fn unlit_sprite_shader() -> ShaderResource {
    static SHADER: OnceLock<ShaderResource> = OnceLock::new();
    SHADER
        .get_or_init(|| {
            ShaderResource::from_str(
                Uuid::new_v4(),
                UNLIT_SPRITE_SHADER_SRC,
                ResourceKind::Embedded,
            )
            .expect("OmfxUnlitSprite shader parse failed")
        })
        .clone()
}

fn make_color_material(color: Color) -> MaterialResource {
    // Custom unlit shader (above): outputs `properties.diffuseColor * diffuseTexture`.
    // Standard shaders won't work — see UNLIT_SPRITE_SHADER_SRC doc comment for why.
    let mut mat = Material::from_shader(unlit_sprite_shader());
    mat.set_property("diffuseColor", MaterialProperty::Color(color));
    MaterialResource::new_embedded(mat)
}
